# Generated by Django 4.1.5 on 2023-02-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankaccount",
            old_name="client",
            new_name="company",
        ),
        migrations.AddField(
            model_name="bank",
            name="code",
            field=models.CharField(default="001", max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="agency",
            field=models.CharField(default="00001", max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="account_number",
            field=models.CharField(max_length=10),
        ),
    ]
