# Generated by Django 4.1.5 on 2023-02-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_rename_client_bankaccount_company_bank_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="name",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.TextField(max_length=20),
        ),
    ]
