# Generated by Django 4.1.5 on 2023-02-06 01:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_bank_name_alter_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
