# Generated by Django 4.1.5 on 2023-02-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_alter_company_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="address_additional_info",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.TextField(default="hello", max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.TextField(default="hello", max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="state",
            field=models.TextField(default="hello", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.TextField(max_length=255),
        ),
    ]
